name: Main

on: push

jobs:
  run-linters-and-test:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      
      - name: Show go version
        run: go version
      
      - name: Format Go Code
        run: go fmt . && gofmt -s -w .

      - name: Run go vet
        run: go vet . github.com/jordan-bonecutter/iter

      - name: Run Go Test
        run: go test .

      - name: Commit linter changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: LinterBot
          commit_message: Linter found style changes
